server:
  port: 18080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://1.94.147.176:3306/classroom?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: kjiolluy711
  redis:
    host: 1.94.147.176
    port: 6379
    password: kjiolluy711
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hzx.entity
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hzx.conc.entity  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true  # 将带有下划线的表字段映射为驼峰格式的实体类属性
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-not-delete-value: 0    # 逻辑未删除值(默认为 0)
      logic-delete-value: 1        # 逻辑已删除值(默认为 1)

logging:
  level:
    com:
      hzx:
        mapper: debug
        service: info
        controller: info


aliyun:
  oss:
    access-key-id: 1232131313
    access-key-secret: 12312312312
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: conc-system


